version: "3"

services:
  webapp:
    build:
      context: .
      dockerfile: ./compose/local/webapp/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - local.env
    ports:
      - "3000:3000"
    networks:
      - istallernet
    depends_on:
      - db
    command: /start.sh

  db:
    image: postgres:11
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    env_file:
      - local.env
    networks:
      - istallernet

volumes:
  postgres_data_local: {}

networks:
  istallernet: {}